### ISSUE TITLE
Doesnt work after two times hacks

### ISSUE THREAD

**Issue by Escheister** [wiire-a/pixiewps#100]
How I can reinstall this program, if this dont work after two pin hacks?

**Comment by rofl0r** [comment]
how did you install it ?

**Comment by Escheister** [comment]
> how did you install it ?

Sudo make install, no? It is my first experience with linux

**Comment by rofl0r** [comment]
> no?

how could i possibly know what you did ?

> Sudo make install

in that case doing it again would "reinstall" it.
