### ISSUE TITLE
[Failed] TP-LINK Wireless Router WR720N

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [wiire-a/pixiewps#101]

**Comment by rofl0r** [comment]
post full pixiewps command line and AP info gathered with wash -j -s (you may censor last 3 octests of mac addr and essid)

**Comment by BL4CKH47H4CK3R** [comment]
Audit Demo For TP-LINK Wireless Router WR720N
PixieDust Can't Find The Pin But WPS Pin Bruteforcing Can Be Done

[*] Audit started at 2019.10.28 04:53:46 (UTC+06:00).
[*] Associating with AP...
[+] Associated with 18:D6:C7:FB:A4:C2 (ESSID: Password Hacked).
[*] Trying pin "12345670"...
[*] Sending EAPOL Start...
[*] Received Identity Request.
[*] Sending Identity Response...
[*] Received WPS Message M1.
[*] E-Nonce: 03F4DC491FFAA26AAC720C26032B620B
[*] PKE: 45AF08AEC81B023155CFDD02B0E25DDD9DE2854EAAC36961178F74CD7D23B8190311ABF6489A5C3A6E2BAA6354A24769BD1A4210CCC3A1BCD49D5C9DAC9547E82F8D22D17A3AF81351A671B166B5B0B58E9F5AA2DE65F98525BBE77700FB0267ABE8919FA52FA3C3FC08A90D53A472BDE11D09252F14BBE879277F418ECD4D1166F4AD2E2B9BA592C8DF38F2D66E2364DAF4A871DE5CC8D9DB1AA43537CFA3B584EE6BCEDFC87A47A74B3F5672A5DB0791ADF8F22FD690DC821F68C41E5C030E
[*] Manufacturer: TP-LINK
[*] Model Name: TL-WR720N
[*] Model Number: 1.0
[*] Serial Number: 1.0
[*] Device Name: TP-LINK Wireless Router WR720N
[*] Sending WPS Message M2...
[*] PKR: 000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002
[*] AuthKey: 6B8560A4654291C20DEB7C6344926039AACD14BA22BB984998E994000F6C62D5
[*] Received WPS Message M3.
[*] E-Hash1: 71BAA4199F7187A353DB6CE59C9316A1D5E25DCE64ECABDA23B59B2D5630469F
[*] E-Hash2: 8096BB7AEA0DF4F9728E5DE1DDCD2F31E5AFBC577FE3CBD8DE251936D7D436BA
[*] Sending WPS Message M4...
[*] Received WSC NACK.
[-] Error: Wrong PIN code.
[*] Sending WSC NACK...
[*] EAP session closed.
[*] Associating with AP...
[+] Associated with 18:D6:C7:FB:A4:C2 (ESSID: Password Hacked).
[*] Starting Pixie Dust attack...
[-] Pixie Dust PIN not found.
[*] Audit stopped at 2019.10.28 04:54:34 (UTC+06:00).

**Comment by rofl0r** [comment]
read my last comment again. i asked for 2 things, you provided something else.
