### ISSUE TITLE
Pixie wps not found 2017

### ISSUE THREAD

**Issue by Hossain007** [wiire-a/pixiewps#52]
Hello guys, can anyone here help me crack this ? I tried putting -f on pixie but still wps not found. All help would be appreciated.
` Trying pin 12345670. [+] E-Nonce: ad:29:7c:0b:1a:5d:57:30:5a:8c:af:0e:ee:5b:79:26 [+] PKE: 57:b9:53:10:9f:a5:e5:5d:15:31:c5:05:2d:4f:42:f5:db:64:d2:d7:e3:33:84:7d:3a:05:fd:60:22:0a:71:67:ae:34:15:13:69:84:41:c2:f3:4c:33:43:e8:33:7f:c8:9f:30:9b:b1:c2:88:4e:9a:d9:d7:2e:6c:ef:4b:98:58:8b:95:4f:e5:ef:27:fd:c8:cb:ce:c8:f1:b3:65:bf:89:e4:6a:06:fc:14:8a:3b:81:4c:9a:3d:68:ef:d5:ad:b6:50:51:95:a3:30:14:ca:0e:5d:99:56:31:70:d2:27:db:ec:42:09:9f:c2:1d:c5:3b:c3:07:be:b5:2d:71:da:6e:a7:5d:20:54:99:a5:c1:78:85:6f:14:91:a2:a4:ef:b4:56:0a:51:c6:e4:74:fa:44:b6:1f:71:bd:6d:29:a0:ee:f7:ec:0f:e6:03:7b:17:6b:b5:60:50:88:fb:1c:95:d9:6d:e9:f5:63:c6:fb:40:60:ca:32:5a:ac:0f:e0:d4:dc [+] R-Nonce: 19:7d:fc:08:75:75:45:01:e5:fa:1a:c0:dd:89:3a:f3 [+] PKR: 2f:b1:6b:2e:44:13:90:98:fb:81:80:7f:bb:3a:f9:fa:c1:14:ce:d9:57:26:67:32:e7:54:55:d3:13:19:dd:30:e4:ac:6a:9d:c9:71:eb:1c:46:ad:f5:ab:be:5a:ef:99:4d:3a:67:cb:01:7e:64:26:d0:3d:34:a7:7a:f1:fb:44:8e:41:a0:d6:97:c2:25:28:8b:cf:b9:77:33:7d:67:4a:b5:9f:bc:00:0f:8c:45:ff:6c:a5:e2:4b:60:06:a8:e7:a2:88:26:cc:6c:e4:c6:1b:b6:74:c4:ed:dd:68:9f:af:9b:d0:03:6b:2e:9e:62:13:c5:70:1b:1a:0e:95:6e:8d:8f:19:55:a9:8e:3a:14:8a:36:22:fe:2b:f3:d1:62:dd:b2:9e:cd:03:e0:bd:7a:61:80:2e:29:3b:05:85:8e:ed:8b:95:86:17:75:e5:7a:42:68:38:84:37:b8:fd:e6:e3:4f:74:15:a0:26:96:8b:cc:23:c7:60:8a:c2:d1:b0:c9 [+] AuthKey: a5:92:96:d8:29:64:d4:ac:6f:80:bc:90:f9:b1:86:18:67:a0:cf:00:0c:63:59:33:a4:73:f7:9f:80:3e:b5:f5 [+] E-Hash1: 88:33:7d:d5:2f:90:85:7b:11:c4:61:85:86:bf:74:9b:61:bf:23:1c:4c:d9:81:1b:8d:73:d2:f9:ce:e8:90:d1 [+] E-Hash2: 2d:ce:d5:b6:76:b5:58:66:a2:fd:fd:5a:bc:e3:55:fd:e6:e6:7c:ff:73:2e:40:cd:d5:d0:95:22:41:2b:e6:d5`

**Comment by wiire-a** [comment]
This is not an issue. Use forums to ask for help.
