### ISSUE TITLE
database

### ISSUE THREAD

**Issue by Asux3** [wiire-a/pixiewps#57]
How to help add more router?

**Comment by soxrok2212** [comment]
Find vulnerabilities in them.

**Comment by rofl0r** [comment]
by researching what random number generator routers use for generating the nonces.
quite certainly that are other vendors apart from the already known ones, which use weak crypto which could be bruteforced, if we know how they do it.
this probably involves looking into/reversing the firmware (but sometimes one is lucky and can even find sourcecode due to GPL enforcement).

**Comment by wiire-a** [comment]
@Asux3 
Vulnerables devices we know of are devices running (Broadcom) **eCos**, but I never got my hands of some data. In particular we know they might have up to 3 different PRNGs (mode **2**, **4**, **5**):
 ```C
#define ECOS_SIMPLE           2
#define ECOS_SIMPLEST         4 /* Not tested */
#define ECOS_KNUTH            5 /* Not tested */
```
Mode **4**, **5** were **never tested**.

We know that one of these vulnerable devices is the **TENDA N304**. Other (cheap) TENDA routers *might be vulnerable* too.

The data I'd need:
* Name and model of the router (name of the firmware if known)
* **Bssid**
* Enrollee nonce (**e-nonce**)
* Registrar nonce (**r-nonce**)
* Enrollee Public key (**pke**)
* Registrar Public key (**pkr**)
* Enrolle hash 1 (**e-hash1**)
* Enrolle hash 2 (**e-hash2**)
* **AuthKey**

Possibly even **Encrypted settings** found in M7 (a complete WPS transaction with known PIN would be needed though).

With this data I would be able to:
* verify that the current implementations work
* possibly add some useful features like the new (`-7`) to crack Diffie-Hellman encryption and recover the WPA from a passive capture.

Other devices that might be vulnerable are other Realtek based access points beside the already implemented in `--mode 3`. But we do have already have some data on those and probably don't need more for now.
