### ISSUE TITLE
--force doesn't print anything to stdout/stderr when not successful ?

### ISSUE THREAD

**Issue by rofl0r** [wiire-a/pixiewps#59]
just got a force run that took over half an hour, and it just silently exited after that, without printing anything. due to that, i was unsure if i might have run into a bug.
when i used --start=06/2001 --end=01/2000 instead, it printed (as expected) a message that the pin was not found.

**Comment by rofl0r** [comment]
seems to be only an issue with a specific glib version glibc-2.12-1.209.el6_9.2.x86_64 and not pixiewps' fault.
setting a breakpoint on printf shows that the code does properly invoke printf, it just doesnt end up on stdout (from inside GNU screen session, wasn't tested outside screen). i tried adding `fflush(stdout);` at the end and `setvbuf(stdout, 0, _IONBF, 0);` just after the beginning of main to no avail. not even `1>&2` would help. the only thing that i found would make the output visible is using `dprintf(2, ...);` which works because stderr is unbuffered by default.

**Comment by wiire-a** [comment]
I'm closing this for now.
