### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by samirx11** [wiire-a/pixiewps#69]
hey tnx wiire-a for script prixiewps for hacking wireless ralink if your problem hacking wireless chipset brodcom plz fix this script pixewps and tnx

**Comment by soxrok2212** [comment]
This is not a pixiewps issue. There are no problems.

**Comment by samirx11** [comment]
No pixiewps hacking wirless chipset ralink good and chipset wireless brodcom no hacking wps not found and wireless" hawei" fix problem hacking   plz fix tnx soxro2212 and wiire-a

**Comment by binarymaster** [comment]
> and chipset wireless brodcom no hacking

Because its PRNG doesn't have known vulnerabilities. Do you know one?
