### ISSUE TITLE
Plz wiire-a how  to use deprecated -S 

### ISSUE THREAD

**Issue by lamghaimima** [wiire-a/pixiewps#71]
how to use this command deprecated -S tnx

**Comment by soxrok2212** [comment]
Don't use it with pixiewps.

**Comment by wiire-a** [comment]
From wikipedia:

> deprecation is the discouragement of use [...] typically because it has been superseded or is **no longer considered** efficient or **safe** – **but without completely removing it or prohibiting its use**

In bold why it's been marked as "deprecated" in this specific case.

See README for why you shouldn't be using *-S* (*--dh-small*).
