### ISSUE TITLE
using pixie pyxie with local install of reaver

### ISSUE THREAD

**Issue by debdrgn** [wiire-a/pixiewps#98]
tltrl: how can launch pyxie to use specific reaver install not system install of reaver?  can we run pyxie without reaver then input pin manual into reaver?

problem1: often virtual machines have problems with wifi tools, airmon suite for example.
problem2: as advanced tools (reaver, pyxie, wash and scripts/tools that depend on them) require specific versions and dependencies that tailor the system configuration very narrowly.

**Comment by rofl0r** [comment]
> how can launch pyxie to use specific reaver install not system install of reaver?

it's usually reaver calling pixiewps, not vice versa.

> can we run pyxie without reaver then input pin manual into reaver?

yes but you gotta collect the cryptographic values needed for pixiewps somehow.

> problem1: often virtual machines have problems with wifi tools, airmon suite for example.

can't help you there.

> problem2: as advanced tools (reaver, pyxie, wash and scripts/tools that depend on them) require specific versions and dependencies that tailor the system configuration very narrowly.

not our problem. if you have problems with tools in your distro, maybe you should talk to the distro guys ?
